### PR TITLE
Updating content and structure of start page

### PR DESCRIPTION
**Pull request by cbroadley-ch**
- Updating all required content of start page to match latest prototype
- Restructuring page layout
- Updating JSON language files - Will need Welsh translations from WLU when available

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by ttingle-ch — APPROVED** [review]
LGTM

**Pull request merged**
