### PR TITLE
Capturing Matomo events by page title

### PR DESCRIPTION
**Pull request by cbroadley-ch**
1. Script added to piwik.njk and function created to display Matomo events based on page titles.
2. Moved piwik.njk from _footer.njk to call script through __meta_header.njk on each page.
3. Calling trackEventBasedOnPageTitle() function on the relevant .njk files to register button clicks based on page title.
4. Adding new constant values for button/link/radio clicks to constants.ts to be called in the above function.
5. Importing constants on /controllers for each page.
6. Creating custom page titles on personal-code.njk and persons-email.njk to exclude identifiable user details on Matomo analytics dashboard.
7. Updating/creating id values on .njk files to include as parameters on trackEventBasedOnPageTitle() function.
8. Removing duplicate data-event-ids from buttons/links on .njk files, to prevent event actions from displaying twice on Matomo

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by ttingle-ch — APPROVED** [review]
LGTM

**Review by atedros-ch — APPROVED** [review]

**Pull request merged**
