### PR TITLE
IDVA5-1563 Fixing navigation issues when user navigates back

### PR DESCRIPTION
**Pull request by ttingle-ch**
Fixed navigation from docs checked group 1 and 2 after check your answers to include the id document details page

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by cbroadley-ch — APPROVED** [review]
LGTM

**Review by rnesbitt-ch — APPROVED** [review]
LGTM

**Pull request merged**
